{
	"id": "ALSA-2022:8162",
	"advisories": [
		{
			"id": "ALSA-2022:8162",
			"title": "Moderate: 389-ds-base security, bug fix, and enhancement update",
			"description": "389 Directory Server is an LDAP version 3 (LDAPv3) compliant server. The base packages include the Lightweight Directory Access Protocol (LDAP) server and command-line utilities for server administration.\n\nThe following packages have been upgraded to a later upstream version: 389-ds-base (2.1.3). (BZ#2061801)\n\nSecurity Fix(es):\n\n* 389-ds-base: sending crafted message could result in DoS (CVE-2022-0918)\n* 389-ds-base: SIGSEGV in sync_repl (CVE-2022-2850)\n* 389-ds-base: expired password was still allowed to access the database (CVE-2022-0996)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.\n\nAdditional Changes:\n\nFor detailed information on changes in this release, see the AlmaLinux Release Notes linked from the References section.",
			"severity": [
				{
					"type": "vendor",
					"source": "errata.almalinux.org",
					"vendor": "Moderate"
				}
			],
			"references": [
				{
					"source": "errata.almalinux.org",
					"url": "https://bugzilla.redhat.com/2064769"
				},
				{
					"source": "errata.almalinux.org",
					"url": "https://bugzilla.redhat.com/2118691"
				},
				{
					"source": "errata.almalinux.org",
					"url": "https://errata.almalinux.org/9/ALSA-2022-8162.html"
				},
				{
					"source": "errata.almalinux.org",
					"url": "https://access.redhat.com/errata/RHSA-2022:8162"
				},
				{
					"source": "errata.almalinux.org",
					"url": "https://access.redhat.com/security/cve/CVE-2022-0918"
				},
				{
					"source": "errata.almalinux.org",
					"url": "https://access.redhat.com/security/cve/CVE-2022-0996"
				},
				{
					"source": "errata.almalinux.org",
					"url": "https://access.redhat.com/security/cve/CVE-2022-2850"
				},
				{
					"source": "errata.almalinux.org",
					"url": "https://bugzilla.redhat.com/2055815"
				}
			],
			"published": "2022-11-15T00:00:00Z",
			"modified": "2022-11-18T03:52:36Z"
		}
	],
	"vulnerabilities": [
		{
			"id": "CVE-2022-0996",
			"references": [
				{
					"source": "errata.almalinux.org",
					"url": "https://access.redhat.com/security/cve/CVE-2022-0996"
				}
			]
		},
		{
			"id": "CVE-2022-2850",
			"references": [
				{
					"source": "errata.almalinux.org",
					"url": "https://access.redhat.com/security/cve/CVE-2022-2850"
				}
			]
		},
		{
			"id": "CVE-2022-0918",
			"references": [
				{
					"source": "errata.almalinux.org",
					"url": "https://access.redhat.com/security/cve/CVE-2022-0918"
				}
			]
		}
	],
	"detection": [
		{
			"ecosystem": "alma:9",
			"vulnerable": true,
			"package": {
				"name": "389-ds-base",
				"architectures": [
					"ppc64le",
					"aarch64",
					"x86_64",
					"s390x"
				]
			},
			"affected": {
				"type": "rpm",
				"range": [
					{
						"lt": "0:2.1.3-4.el9_1"
					}
				],
				"fixed": [
					"0:2.1.3-4.el9_1"
				]
			}
		},
		{
			"ecosystem": "alma:9",
			"vulnerable": true,
			"package": {
				"name": "389-ds-base-libs",
				"architectures": [
					"ppc64le",
					"aarch64",
					"x86_64",
					"s390x"
				]
			},
			"affected": {
				"type": "rpm",
				"range": [
					{
						"lt": "0:2.1.3-4.el9_1"
					}
				],
				"fixed": [
					"0:2.1.3-4.el9_1"
				]
			}
		},
		{
			"ecosystem": "alma:9",
			"vulnerable": true,
			"package": {
				"name": "python3-lib389",
				"architectures": [
					"noarch"
				]
			},
			"affected": {
				"type": "rpm",
				"range": [
					{
						"lt": "0:2.1.3-4.el9_1"
					}
				],
				"fixed": [
					"0:2.1.3-4.el9_1"
				]
			}
		}
	],
	"data_source": "alma-errata"
}
